### ISSUE TITLE
Failed when installing using pip

### ISSUE THREAD

**Issue by bbanfai** [Ben-Epstein/spacy-to-hf#2]
Dear Ben,

It seems to be an issue with the dependecies when installing your module using pip:
Collecting spacy-to-hf
  Using cached spacy_to_hf-0.0.3-py3-none-any.whl (10 kB)
Collecting spacy<3 (from spacy-to-hf)
  Using cached spacy-2.3.9-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.9 MB)
Collecting pytokenizations (from spacy-to-hf)
  Using cached pytokenizations-0.8.4.tar.gz (3.8 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Best regards,
Balazs

**Comment by Ben-Epstein** [comment]
@bbanfai what version of python are you running?

**Comment by franz101** [comment]
I fixed it sir.

**Comment by franz101** [comment]
It's the same issue as here:
https://github.com/explosion/tokenizations/issues/92

I forgot but somewhere the author wrote he moved it to:
https://github.com/explosion/spacy-alignments?tab=readme-ov-file

**Comment by Ben-Epstein** [comment]
@bbanfai just released 0.0.4, this should be addressed :)
